### ISSUE TITLE
消息可靠性方案设计

### ISSUE THREAD

**Issue by IamNotShady** [raven-im/raven#1]
不乱序，不丢失，不重复,99.999%

**Comment by bbpatience** [comment]
第一版讨论:

#### 发送方按照需求，选择合理的QOS

> AT_MOST_ONCE(0), AT_LEAST_ONCE(1), EXACTLY_ONCE(2)


1. 如何保证消息不丢失
   * 采用 AT_LEAST_ONCE
   * 支持消息重传，直到收到ACK
   * 不保证重复
   * 可由接收方做去重处理
2. 如何保证消息不重复
    * 若采用 AT_LEAST_ONCE，由接收方去重
    * 若采用 AT_MOST_ONCE，不用去重
    
3. 如何保证消息不乱序
    * 根据 server时间为序
    * 消息上来后，根据targetId算落点, 然后由服务器生成messageId 和 统一时间戳timestamp
    * 单聊targetId == receiver userId,落到一台服务器，后续所有消息均落在同一台服务器，利用该台服务器时间，可以做到有序
    * 群聊相同，targetId == groupId
