### ISSUE TITLE
二期任务项

### ISSUE THREAD

**Issue by bbpatience** [raven-im/raven#22]
缓存和配置中心3期考虑

**Comment by IamNotShady** [comment]
- [x] access和single/group通信方式修改为 aceess为server singel/group为client
- [x] 消息上行: access收到消息推到MQ access收到mq回复的ack 然后回客户端ack
- [x] 消息下行：single/group从mq收到消息>>业务处理>>消息落盘 找到aceess推送消息
- [ ] 消息不丢失保证：access推送失败重试机制
- [X] 消息不重复：access存储客户端消息ID，通过该ID判断重复
- [x] 消息有序性：按照消息服务端ID或收到消息时间排序都可行

**Comment by IamNotShady** [comment]
消息协议支持json

**Comment by IamNotShady** [comment]
- [x] 增加zuul过滤器
- [x] 路由支持websocket
