### ISSUE TITLE
一致性hash通用方法

### ISSUE THREAD

**Issue by IamNotShady** [raven-im/raven#4]

**Comment by bbpatience** [comment]
一致性Hash.

h = Hash(key) % N

为了在添加和删除节点时， 不至于每个节点数据都要迁移， 所以引入 一致性Hash. 解决了容错性和可扩展性。

为了解决数据倾斜，引入 虚拟节点，一个物理节点映射为N个 虚拟节点， 均衡分布在Hash环上。 http://blog.codinglabs.org/articles/consistent-hashing.html

一致性Hash的实现: Ketama算法 http://codelog.me/2015/10/12/consistent-hash-ketama/

**Comment by IamNotShady** [comment]
已实现 cef6d77935f2843b792b97e0028459f4032de846
